
import streamlit as st
st.set_page_config(page_title="GemmaVision-QuantAdvisor", layout="wide")
st.sidebar.image("https://www.quantuniversity.com/assets/img/logo5.jpg")
st.sidebar.divider()
st.title("GemmaVision-QuantAdvisor")
st.divider()

st.markdown("""
In this lab, we will explore the GemmaVision-QuantAdvisor application, designed for Financial Data Engineers to evaluate and compare Gemma 3 models. This platform offers insights into multimodal capabilities, quantization strategies, and performance benchmarks, facilitating informed deployment decisions for financial document understanding tasks.
""")

page = st.sidebar.selectbox(label="Navigation", options=["Home", "Model Overview", "Quantization Strategies", "Multimodal Document Understanding", "Performance Benchmarks"])

if page == "Home":
    from application_pages.home_page import main
    main()
elif page == "Model Overview":
    from application_pages.model_overview import main
    main()
elif page == "Quantization Strategies":
    from application_pages.quantization_strategies import main
    main()
elif page == "Multimodal Document Understanding":
    from application_pages.multimodal_document_understanding import main
    main()
elif page == "Performance Benchmarks":
    from application_pages.performance_benchmarks import main
    main()


# License
st.caption('''
---
## QuantUniversity License

© QuantUniversity 2025  
This notebook was created for **educational purposes only** and is **not intended for commercial use**.  

- You **may not copy, share, or redistribute** this notebook **without explicit permission** from QuantUniversity.  
- You **may not delete or modify this license cell** without authorization.  
- This notebook was generated using **QuCreate**, an AI-powered assistant.  
- Content generated by AI may contain **hallucinated or incorrect information**. Please **verify before using**.  

All rights reserved. For permissions or commercial licensing, contact: [info@quantuniversity.com](mailto:info@quantuniversity.com)
''')
